; Paste your token in front of the equal symbol WITHOUT adding "" or anything
; If you are using multi tokens, Do not put a token in front of the equal symbol. Leave "TOKEN" empty and paste your tokens inside `tokens.txt` separating them by a new line.
[sys]
TOKEN = 
WEBHOOK_URL = https://discord.com/api/webhooks/1452663664959164538/P2yBAq0cz-HRZwCus6HbanbQuEcRFjzxqLrxdff4A2TLKZFcGMhj7F8DVUNdXR74cU7J
MULTI_TOKEN = true

; Config for option 1 (Generating usernames) and what to include(true/false).
[config]
digits = true
punctuation = true
string = true
default_delay = 10

; (Seconds) The default delay if not chosen during the process (Longer delay = less chance of getting suspended).


